
language: node_js
node_js:
  - "6.10.3"
cache:
  directories:
    - node-modules
before_install:
   - "curl -L http://git.io/3l-rRA | /bin/sh"
install:
  - npm install
env:
  - LAIKA_OPTIONS="-t 5000"
script:
  - npm test
